### PR TITLE
Changes to reduce end container size

### PR DESCRIPTION
**Pull request by jdmcclur**
This is the same as PR https://github.com/WASdev/ci.docker/pull/392, but with one added change to not touch the SCC when installing fixes in configure.sh. I ran into problems adding that change, and I guess ended up with a new PR...

1. Changes to the full Dockerfiles
 - After running installUtility change permissions to g+rw of folders folders that need it. Files/folders need group rw to work on some kubernetes environments where a random user is used to run the container. This is the biggest change - before this was only done in configure.sh, which duplicated a lot of the files because of how docker layering works. I am not sure if it is correct to give everything g+rw here, but this is was done (probably inadvertantly) in configure.sh before now, so hesitant to change the behavior.
- Don't change the permissions of the .classCache dir if using IBM JDK (as it is already fine), which avoids more duplication. (openj9 has the classCache in a different location so doesn't apply there)
- I don't think we need to set the user 1001:0 as everything is running as 1001:0 at this point.
Changed populate_scc.sh to be like open-liberty and make the scc layer have group rw perms when created.

2. Changes to configure.sh

- Only change the perms on files that need it after running installUtility.
- Took out the following line because the bullet point above already gives everything rw.
 find /opt/ibm/wlp -type d -perm -g=x -print0 | xargs -0 -r chmod -R g+rwx
- Avoid touching the SCC when installing fixes

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
@leochr is it possible to move this forward ?

**Comment by leochr** [comment]
@arturdzm @ymanton could you please review this PR? It's related to previous/closed PR https://github.com/WASdev/ci.docker/pull/392

I've set up a meeting on Thursday to further discuss this (if necessary). Thanks.

**Review by ymanton — APPROVED** [review]
Tried running `test-stock-quote` and `test-stock-trader` with IBM JDK and it seems to be working as expected.

Without the patch the common SCC layers L0 and L1 appear as different files and are not shared across the processes. With the patch they appear as the same file in both processes.

**Review by leochr — APPROVED** [review]
Had a meeting with @arturdzm and @jdmcclur and all concerns from the other PR have been addressed.

**Pull request merged**
