### PR TITLE
WIP: add social login config snippet

### PR DESCRIPTION
**Pull request by brutif**

### CODE REVIEW

**Comment by brutif** [comment]
@arthurdm how do I build this locally to check my work?

**Comment by brutif** [comment]
partially addresses https://github.com/OpenLiberty/open-liberty-operator/issues/98

**Comment by arthurdm** [comment]
hey @brutif - now that the OL side has been merged, I am guessing this PR will be updated with those contents?

**Comment by brutif** [comment]
@arthurdm yes that's the plan,  I may wait a week or so until OL side testing with operator has completed just in case we find anything that needs adjusting.  I know there's no WL operator but both WL and OL should be consistent.

**Comment by leochr** [comment]
Resolved by https://github.com/WASdev/ci.docker/pull/338

**Pull request closed without merging**
